// <auto-generated />
using System;
using CloudCure.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CloudCure.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CloudCureDbContext))]
    [Migration("20260905062618_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CloudCure.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("line1");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("line2");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("StateProvince")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state_province");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_addresses_person_id");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.AllergyReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string[]>("Aliases")
                        .HasColumnType("text[]")
                        .HasColumnName("aliases");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("canonical_name");

                    b.HasKey("Id")
                        .HasName("pk_allergy_reference");

                    b.HasIndex("CanonicalName")
                        .IsUnique()
                        .HasDatabaseName("ix_allergy_reference_canonical_name");

                    b.ToTable("allergy_reference", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiefComplaint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chief_complaint");

                    b.Property<int>("EncounterId")
                        .HasColumnType("integer")
                        .HasColumnName("encounter_id");

                    b.Property<string>("HistoryOfPresentIllness")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("history_of_present_illness");

                    b.Property<int>("PainScale")
                        .HasColumnType("integer")
                        .HasColumnName("pain_scale");

                    b.HasKey("Id")
                        .HasName("pk_assessments");

                    b.HasIndex("EncounterId")
                        .IsUnique()
                        .HasDatabaseName("ix_assessments_encounter_id");

                    b.ToTable("assessments", null, t =>
                        {
                            t.HasCheckConstraint("ck_assessments_pain_scale", "pain_scale BETWEEN 0 AND 10");
                        });
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.AssessmentPainPoint", b =>
                {
                    b.Property<int>("AssessmentId")
                        .HasColumnType("integer")
                        .HasColumnName("assessment_id");

                    b.Property<int>("BodyRegionId")
                        .HasColumnType("integer")
                        .HasColumnName("body_region_id");

                    b.HasKey("AssessmentId", "BodyRegionId")
                        .HasName("pk_assessment_pain_points");

                    b.HasIndex("BodyRegionId")
                        .HasDatabaseName("ix_assessment_pain_points_body_region_id");

                    b.ToTable("assessment_pain_points", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_person_id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("text")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("text")
                        .HasColumnName("before_json");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_log_entity_type_entity_id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.AuthIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth0Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("auth0subject");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_identities");

                    b.HasIndex("Auth0Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_identities_auth0subject");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_auth_identities_person_id");

                    b.ToTable("auth_identities", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.BodyRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("RegionGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region_group");

                    b.HasKey("Id")
                        .HasName("pk_body_regions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_body_regions_code");

                    b.ToTable("body_regions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "head",
                            DisplayName = "Head",
                            RegionGroup = "Head/Neck"
                        },
                        new
                        {
                            Id = 2,
                            Code = "face",
                            DisplayName = "Face",
                            RegionGroup = "Head/Neck"
                        },
                        new
                        {
                            Id = 3,
                            Code = "neck",
                            DisplayName = "Neck",
                            RegionGroup = "Head/Neck"
                        },
                        new
                        {
                            Id = 4,
                            Code = "chest",
                            DisplayName = "Chest",
                            RegionGroup = "Torso"
                        },
                        new
                        {
                            Id = 5,
                            Code = "abdomen",
                            DisplayName = "Abdomen",
                            RegionGroup = "Torso"
                        },
                        new
                        {
                            Id = 6,
                            Code = "pelvis",
                            DisplayName = "Pelvis",
                            RegionGroup = "Torso"
                        },
                        new
                        {
                            Id = 7,
                            Code = "upper_back",
                            DisplayName = "Upper Back",
                            RegionGroup = "Back"
                        },
                        new
                        {
                            Id = 8,
                            Code = "lower_back",
                            DisplayName = "Lower Back",
                            RegionGroup = "Back"
                        },
                        new
                        {
                            Id = 9,
                            Code = "shoulder_left",
                            DisplayName = "Left Shoulder",
                            RegionGroup = "Upper Limbs"
                        },
                        new
                        {
                            Id = 10,
                            Code = "shoulder_right",
                            DisplayName = "Right Shoulder",
                            RegionGroup = "Upper Limbs"
                        },
                        new
                        {
                            Id = 11,
                            Code = "arm_left",
                            DisplayName = "Left Arm",
                            RegionGroup = "Upper Limbs"
                        },
                        new
                        {
                            Id = 12,
                            Code = "arm_right",
                            DisplayName = "Right Arm",
                            RegionGroup = "Upper Limbs"
                        },
                        new
                        {
                            Id = 13,
                            Code = "hand_left",
                            DisplayName = "Left Hand",
                            RegionGroup = "Upper Limbs"
                        },
                        new
                        {
                            Id = 14,
                            Code = "hand_right",
                            DisplayName = "Right Hand",
                            RegionGroup = "Upper Limbs"
                        },
                        new
                        {
                            Id = 15,
                            Code = "hip_left",
                            DisplayName = "Left Hip",
                            RegionGroup = "Lower Limbs"
                        },
                        new
                        {
                            Id = 16,
                            Code = "hip_right",
                            DisplayName = "Right Hip",
                            RegionGroup = "Lower Limbs"
                        },
                        new
                        {
                            Id = 17,
                            Code = "leg_left",
                            DisplayName = "Left Leg",
                            RegionGroup = "Lower Limbs"
                        },
                        new
                        {
                            Id = 18,
                            Code = "leg_right",
                            DisplayName = "Right Leg",
                            RegionGroup = "Lower Limbs"
                        },
                        new
                        {
                            Id = 19,
                            Code = "foot_left",
                            DisplayName = "Left Foot",
                            RegionGroup = "Lower Limbs"
                        },
                        new
                        {
                            Id = 20,
                            Code = "foot_right",
                            DisplayName = "Right Foot",
                            RegionGroup = "Lower Limbs"
                        });
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.ConditionReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string[]>("Aliases")
                        .HasColumnType("text[]")
                        .HasColumnName("aliases");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("canonical_name");

                    b.HasKey("Id")
                        .HasName("pk_condition_reference");

                    b.HasIndex("CanonicalName")
                        .IsUnique()
                        .HasDatabaseName("ix_condition_reference_canonical_name");

                    b.ToTable("condition_reference", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DoctorDiagnosisText")
                        .HasColumnType("text")
                        .HasColumnName("doctor_diagnosis_text");

                    b.Property<int>("EncounterId")
                        .HasColumnType("integer")
                        .HasColumnName("encounter_id");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<int?>("FinalizedByStaffMemberId")
                        .HasColumnType("integer")
                        .HasColumnName("finalized_by_staff_member_id");

                    b.Property<string>("RecommendedTreatment")
                        .HasColumnType("text")
                        .HasColumnName("recommended_treatment");

                    b.HasKey("Id")
                        .HasName("pk_diagnoses");

                    b.HasIndex("EncounterId")
                        .IsUnique()
                        .HasDatabaseName("ix_diagnoses_encounter_id");

                    b.HasIndex("FinalizedByStaffMemberId")
                        .HasDatabaseName("ix_diagnoses_finalized_by_staff_member_id");

                    b.ToTable("diagnoses", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Encounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttendingStaffMemberId")
                        .HasColumnType("integer")
                        .HasColumnName("attending_staff_member_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_encounters");

                    b.HasIndex("AttendingStaffMemberId")
                        .HasDatabaseName("ix_encounters_attending_staff_member_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_encounters_patient_id");

                    b.ToTable("encounters", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.MedicationReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string[]>("Aliases")
                        .HasColumnType("text[]")
                        .HasColumnName("aliases");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("canonical_name");

                    b.HasKey("Id")
                        .HasName("pk_medication_reference");

                    b.HasIndex("CanonicalName")
                        .IsUnique()
                        .HasDatabaseName("ix_medication_reference_canonical_name");

                    b.ToTable("medication_reference", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhoneE164")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("emergency_contact_phone_e164");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_person_id");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.PatientAllergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FreeTextName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("free_text_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer")
                        .HasColumnName("reference_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("Id")
                        .HasName("pk_patient_allergies");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_patient_allergies_patient_id");

                    b.HasIndex("ReferenceId")
                        .HasDatabaseName("ix_patient_allergies_reference_id");

                    b.ToTable("patient_allergies", null, t =>
                        {
                            t.HasCheckConstraint("ck_patient_allergies_reference_or_free_text", "reference_id IS NOT NULL OR free_text_name IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.PatientCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FreeTextName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("free_text_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer")
                        .HasColumnName("reference_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("Id")
                        .HasName("pk_patient_conditions");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_patient_conditions_patient_id");

                    b.HasIndex("ReferenceId")
                        .HasDatabaseName("ix_patient_conditions_reference_id");

                    b.ToTable("patient_conditions", null, t =>
                        {
                            t.HasCheckConstraint("ck_patient_conditions_reference_or_free_text", "reference_id IS NOT NULL OR free_text_name IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.PatientMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FreeTextName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("free_text_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer")
                        .HasColumnName("reference_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("Id")
                        .HasName("pk_patient_medications");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_patient_medications_patient_id");

                    b.HasIndex("ReferenceId")
                        .HasDatabaseName("ix_patient_medications_reference_id");

                    b.ToTable("patient_medications", null, t =>
                        {
                            t.HasCheckConstraint("ck_patient_medications_reference_or_free_text", "reference_id IS NOT NULL OR free_text_name IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.PatientSurgery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FreeTextName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("free_text_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer")
                        .HasColumnName("reference_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("Id")
                        .HasName("pk_patient_surgeries");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_patient_surgeries_patient_id");

                    b.HasIndex("ReferenceId")
                        .HasDatabaseName("ix_patient_surgeries_reference_id");

                    b.ToTable("patient_surgeries", null, t =>
                        {
                            t.HasCheckConstraint("ck_patient_surgeries_reference_or_free_text", "reference_id IS NOT NULL OR free_text_name IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneE164")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_e164");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_people_email")
                        .HasFilter("email IS NOT NULL");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.PersonRole", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_person_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("PersonId", "RoleId")
                        .HasName("pk_person_roles");

                    b.HasIndex("GrantedByPersonId")
                        .HasDatabaseName("ix_person_roles_granted_by_person_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_person_roles_role_id");

                    b.ToTable("person_roles", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Role", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "Nurse"
                        },
                        new
                        {
                            Id = (short)3,
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = (short)4,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CompletedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by_person_id");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("integer")
                        .HasColumnName("encounter_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<int>("ScreeningTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("screening_template_id");

                    b.HasKey("Id")
                        .HasName("pk_screenings");

                    b.HasIndex("CompletedByPersonId")
                        .HasDatabaseName("ix_screenings_completed_by_person_id");

                    b.HasIndex("EncounterId")
                        .HasDatabaseName("ix_screenings_encounter_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_screenings_patient_id");

                    b.HasIndex("ScreeningTemplateId")
                        .HasDatabaseName("ix_screenings_screening_template_id");

                    b.ToTable("screenings", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.ScreeningAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AnswerBool")
                        .HasColumnType("boolean")
                        .HasColumnName("answer_bool");

                    b.Property<decimal?>("AnswerNumber")
                        .HasColumnType("numeric")
                        .HasColumnName("answer_number");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("integer")
                        .HasColumnName("screening_id");

                    b.Property<int>("ScreeningQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("screening_question_id");

                    b.HasKey("Id")
                        .HasName("pk_screening_answers");

                    b.HasIndex("ScreeningQuestionId")
                        .HasDatabaseName("ix_screening_answers_screening_question_id");

                    b.HasIndex("ScreeningId", "ScreeningQuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_screening_answers_screening_id_screening_question_id");

                    b.ToTable("screening_answers", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.ScreeningQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerType")
                        .HasColumnType("integer")
                        .HasColumnName("answer_type");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<int>("ScreeningTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("screening_template_id");

                    b.HasKey("Id")
                        .HasName("pk_screening_questions");

                    b.HasIndex("ScreeningTemplateId")
                        .HasDatabaseName("ix_screening_questions_screening_template_id");

                    b.ToTable("screening_questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerType = 1,
                            DisplayOrder = 1,
                            QuestionText = "Are you currently experiencing a fever, cough, or shortness of breath?",
                            ScreeningTemplateId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnswerType = 1,
                            DisplayOrder = 2,
                            QuestionText = "Are you currently isolating or quarantining due to a COVID-19 exposure or diagnosis?",
                            ScreeningTemplateId = 1
                        },
                        new
                        {
                            Id = 3,
                            AnswerType = 1,
                            DisplayOrder = 3,
                            QuestionText = "Has anyone in your household experienced any COVID-19 symptoms in the last 14 days?",
                            ScreeningTemplateId = 1
                        },
                        new
                        {
                            Id = 4,
                            AnswerType = 1,
                            DisplayOrder = 4,
                            QuestionText = "Have you tested positive for COVID-19 in the last 10 days?",
                            ScreeningTemplateId = 1
                        },
                        new
                        {
                            Id = 5,
                            AnswerType = 1,
                            DisplayOrder = 5,
                            QuestionText = "Have you traveled outside the country in the last 14 days?",
                            ScreeningTemplateId = 1
                        });
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.ScreeningTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_screening_templates");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_screening_templates_code");

                    b.ToTable("screening_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "covid19_v1",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Title = "COVID-19 Screening"
                        });
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.StaffMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EducationDegree")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("education_degree");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("room_number");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("specialization");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("WorkEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("work_email");

                    b.HasKey("Id")
                        .HasName("pk_staff_members");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_members_person_id");

                    b.HasIndex("WorkEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_members_work_email");

                    b.ToTable("staff_members", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.SurgeryReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string[]>("Aliases")
                        .HasColumnType("text[]")
                        .HasColumnName("aliases");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("canonical_name");

                    b.HasKey("Id")
                        .HasName("pk_surgery_reference");

                    b.HasIndex("CanonicalName")
                        .IsUnique()
                        .HasDatabaseName("ix_surgery_reference_canonical_name");

                    b.ToTable("surgery_reference", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Vitals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiastolicMmHg")
                        .HasColumnType("integer")
                        .HasColumnName("diastolic_mm_hg");

                    b.Property<int>("EncounterId")
                        .HasColumnType("integer")
                        .HasColumnName("encounter_id");

                    b.Property<int>("HeartRateBpm")
                        .HasColumnType("integer")
                        .HasColumnName("heart_rate_bpm");

                    b.Property<int>("HeightUnit")
                        .HasColumnType("integer")
                        .HasColumnName("height_unit");

                    b.Property<decimal>("HeightValue")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("height_value");

                    b.Property<decimal>("OxygenSaturationPct")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("oxygen_saturation_pct");

                    b.Property<int>("RespiratoryRateBpm")
                        .HasColumnType("integer")
                        .HasColumnName("respiratory_rate_bpm");

                    b.Property<int>("SystolicMmHg")
                        .HasColumnType("integer")
                        .HasColumnName("systolic_mm_hg");

                    b.Property<int>("TemperatureUnit")
                        .HasColumnType("integer")
                        .HasColumnName("temperature_unit");

                    b.Property<decimal>("TemperatureValue")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("temperature_value");

                    b.Property<int>("WeightUnit")
                        .HasColumnType("integer")
                        .HasColumnName("weight_unit");

                    b.Property<decimal>("WeightValue")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("weight_value");

                    b.HasKey("Id")
                        .HasName("pk_vitals");

                    b.HasIndex("EncounterId")
                        .IsUnique()
                        .HasDatabaseName("ix_vitals_encounter_id");

                    b.ToTable("vitals", (string)null);
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Address", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.Person", "Person")
                        .WithOne("Address")
                        .HasForeignKey("CloudCure.Domain.Entities.Address", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_people_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Assessment", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.Encounter", "Encounter")
                        .WithOne("Assessment")
                        .HasForeignKey("CloudCure.Domain.Entities.Assessment", "EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessments_encounters_encounter_id");

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.AssessmentPainPoint", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.Assessment", "Assessment")
                        .WithMany("PainPoints")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_pain_points_assessments_assessment_id");

                    b.HasOne("CloudCure.Domain.Entities.BodyRegion", "BodyRegion")
                        .WithMany("AssessmentPainPoints")
                        .HasForeignKey("BodyRegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_pain_points_body_regions_body_region_id");

                    b.Navigation("Assessment");

                    b.Navigation("BodyRegion");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.AuthIdentity", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.Person", "Person")
                        .WithMany("AuthIdentities")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_identities_people_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Diagnosis", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.Encounter", "Encounter")
                        .WithOne("Diagnosis")
                        .HasForeignKey("CloudCure.Domain.Entities.Diagnosis", "EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diagnoses_encounters_encounter_id");

                    b.HasOne("CloudCure.Domain.Entities.StaffMember", "FinalizedByStaffMember")
                        .WithMany()
                        .HasForeignKey("FinalizedByStaffMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_diagnoses_staff_members_finalized_by_staff_member_id");

                    b.Navigation("Encounter");

                    b.Navigation("FinalizedByStaffMember");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Encounter", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.StaffMember", "AttendingStaffMember")
                        .WithMany("AttendedEncounters")
                        .HasForeignKey("AttendingStaffMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_encounters_staff_members_attending_staff_member_id");

                    b.HasOne("CloudCure.Domain.Entities.Patient", "Patient")
                        .WithMany("Encounters")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_encounters_patients_patient_id");

                    b.Navigation("AttendingStaffMember");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Patient", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.Person", "Person")
                        .WithOne("Patient")
                        .HasForeignKey("CloudCure.Domain.Entities.Patient", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patients_people_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.PatientAllergy", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.Patient", "Patient")
                        .WithMany("Allergies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_allergies_patients_patient_id");

                    b.HasOne("CloudCure.Domain.Entities.AllergyReference", "Reference")
                        .WithMany("PatientAllergies")
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_patient_allergies_allergy_references_reference_id");

                    b.Navigation("Patient");

                    b.Navigation("Reference");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.PatientCondition", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.Patient", "Patient")
                        .WithMany("Conditions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_conditions_patients_patient_id");

                    b.HasOne("CloudCure.Domain.Entities.ConditionReference", "Reference")
                        .WithMany("PatientConditions")
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_patient_conditions_condition_references_reference_id");

                    b.Navigation("Patient");

                    b.Navigation("Reference");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.PatientMedication", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.Patient", "Patient")
                        .WithMany("Medications")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_medications_patients_patient_id");

                    b.HasOne("CloudCure.Domain.Entities.MedicationReference", "Reference")
                        .WithMany("PatientMedications")
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_patient_medications_medication_references_reference_id");

                    b.Navigation("Patient");

                    b.Navigation("Reference");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.PatientSurgery", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.Patient", "Patient")
                        .WithMany("Surgeries")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_surgeries_patients_patient_id");

                    b.HasOne("CloudCure.Domain.Entities.SurgeryReference", "Reference")
                        .WithMany("PatientSurgeries")
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_patient_surgeries_surgery_references_reference_id");

                    b.Navigation("Patient");

                    b.Navigation("Reference");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.PersonRole", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.Person", "GrantedByPerson")
                        .WithMany()
                        .HasForeignKey("GrantedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_person_roles_people_granted_by_person_id");

                    b.HasOne("CloudCure.Domain.Entities.Person", "Person")
                        .WithMany("PersonRoles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_roles_people_person_id");

                    b.HasOne("CloudCure.Domain.Entities.Role", "Role")
                        .WithMany("PersonRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_person_roles_roles_role_id");

                    b.Navigation("GrantedByPerson");

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Screening", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.Person", "CompletedByPerson")
                        .WithMany()
                        .HasForeignKey("CompletedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_screenings_people_completed_by_person_id");

                    b.HasOne("CloudCure.Domain.Entities.Encounter", "Encounter")
                        .WithMany("Screenings")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_screenings_encounters_encounter_id");

                    b.HasOne("CloudCure.Domain.Entities.Patient", "Patient")
                        .WithMany("Screenings")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_screenings_patients_patient_id");

                    b.HasOne("CloudCure.Domain.Entities.ScreeningTemplate", "ScreeningTemplate")
                        .WithMany("Screenings")
                        .HasForeignKey("ScreeningTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_screenings_screening_templates_screening_template_id");

                    b.Navigation("CompletedByPerson");

                    b.Navigation("Encounter");

                    b.Navigation("Patient");

                    b.Navigation("ScreeningTemplate");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.ScreeningAnswer", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.Screening", "Screening")
                        .WithMany("Answers")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_screening_answers_screenings_screening_id");

                    b.HasOne("CloudCure.Domain.Entities.ScreeningQuestion", "ScreeningQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("ScreeningQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_screening_answers_screening_questions_screening_question_id");

                    b.Navigation("Screening");

                    b.Navigation("ScreeningQuestion");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.ScreeningQuestion", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.ScreeningTemplate", "ScreeningTemplate")
                        .WithMany("Questions")
                        .HasForeignKey("ScreeningTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_screening_questions_screening_templates_screening_template_");

                    b.Navigation("ScreeningTemplate");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.StaffMember", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.Person", "Person")
                        .WithOne("StaffMember")
                        .HasForeignKey("CloudCure.Domain.Entities.StaffMember", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_members_people_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Vitals", b =>
                {
                    b.HasOne("CloudCure.Domain.Entities.Encounter", "Encounter")
                        .WithOne("Vitals")
                        .HasForeignKey("CloudCure.Domain.Entities.Vitals", "EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vitals_encounters_encounter_id");

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.AllergyReference", b =>
                {
                    b.Navigation("PatientAllergies");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Assessment", b =>
                {
                    b.Navigation("PainPoints");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.BodyRegion", b =>
                {
                    b.Navigation("AssessmentPainPoints");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.ConditionReference", b =>
                {
                    b.Navigation("PatientConditions");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Encounter", b =>
                {
                    b.Navigation("Assessment");

                    b.Navigation("Diagnosis");

                    b.Navigation("Screenings");

                    b.Navigation("Vitals");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.MedicationReference", b =>
                {
                    b.Navigation("PatientMedications");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("Conditions");

                    b.Navigation("Encounters");

                    b.Navigation("Medications");

                    b.Navigation("Screenings");

                    b.Navigation("Surgeries");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Person", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("AuthIdentities");

                    b.Navigation("Patient");

                    b.Navigation("PersonRoles");

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Role", b =>
                {
                    b.Navigation("PersonRoles");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.Screening", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.ScreeningQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.ScreeningTemplate", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.StaffMember", b =>
                {
                    b.Navigation("AttendedEncounters");
                });

            modelBuilder.Entity("CloudCure.Domain.Entities.SurgeryReference", b =>
                {
                    b.Navigation("PatientSurgeries");
                });
#pragma warning restore 612, 618
        }
    }
}
